export const flightData = [
    {
      id: 1,
      route: "Jakarta - Paris",
      price: "Rp. 12.000.000",
      discount: "-20%",
      image: "/images/balikpapan.svg",
      isFavorite: true,
    },
    {
      id: 2,
      route: "Surabaya - Belanda",
      price: "Rp. 12.000.000",
      discount: "-20%",
      image: "/images/italia.svg",
      isFavorite: true,
    },
    {
      id: 3,
      route: "Balikpapan - Bali",
      price: "Rp. 12.000.000",
      discount: "-20%",
      image: "/images/jakarta.svg",
      isFavorite: true,
    },
    {
      id: 4,
      route: "Bandung - Tokyo",
      price: "Rp. 15.000.000",
      discount: "-15%",
      image: "/images/italia.svg",
      isFavorite: false,
    },
    {
      id: 5,
      route: "Yogyakarta - Sydney",
      price: "Rp. 20.000.000",
      discount: "-25%",
      image: "/images/italia.svg",
      isFavorite: false,
    },
    {
      id: 6,
      route: "Medan - Singapore",
      price: "Rp. 10.000.000",
      discount: "-10%",
      image: "/images/italia.svg",
      isFavorite: true,
    },
    {
      id: 7,
      route: "Denpasar - Hong Kong",
      price: "Rp. 18.000.000",
      discount: "-30%",
      image: "/images/italia.svg",
      isFavorite: false,
    },
    {
      id: 8,
      route: "Semarang - Seoul",
      price: "Rp. 16.000.000",
      discount: "-20%",
      image: "/images/italia.svg",
      isFavorite: false,
    },
    {
      id: 9,
      route: "Palembang - New York",
      price: "Rp. 25.000.000",
      discount: "-15%",
      image: "/images/italia.svg",
      isFavorite: false,
    },
    {
      id: 10,
      route: "Makassar - Dubai",
      price: "Rp. 22.000.000",
      discount: "-10%",
      image: "/images/italia.svg",
      isFavorite: true,
    },
  ];
  