export const testimonialData = [
    {
      id: 1,
      name: "Alifah Nur Aisyah",
      maskapai: "Maskapai Garuda Indonesia",
      rute: "Penerbangan Balikpapan Jakarta",
      ulasan: "Penerbangan Garuda Indonesia memang terbaik, kami mendapatkan makanan yang enak-enak. Btw, cookiesnya dijual umum ga ya? 😋",
      rating: 5,
    },
    {
      id: 2,
      name: "Rizky Pratama",
      maskapai: "Maskapai Lion Air",
      rute: "Penerbangan Surabaya Bali",
      ulasan: "Lumayan untuk harga tiket yang murah, cuma delay 30 menit.",
      rating: 3,
    },
    {
      id: 3,
      name: "Dewi Lestari",
      maskapai: "Maskapai Citilink",
      rute: "Penerbangan Yogyakarta Jakarta",
      ulasan: "Pelayanan ramah dan kabin bersih, sangat memuaskan!",
      rating: 4,
    },
    {
      id: 4,
      name: "Budi Santoso",
      maskapai: "Maskapai AirAsia",
      rute: "Penerbangan Jakarta Kuala Lumpur",
      ulasan: "Harga tiket bersahabat dan perjalanan lancar.",
      rating: 4,
    },
    {
      id: 5,
      name: "Citra Ayu",
      maskapai: "Maskapai Garuda Indonesia",
      rute: "Penerbangan Denpasar Jakarta",
      ulasan: "Flight-nya nyaman banget, makanan dan entertainment oke!",
      rating: 5,
    },
    {
      id: 6,
      name: "Fadli Akbar",
      maskapai: "Maskapai Batik Air",
      rute: "Penerbangan Medan Jakarta",
      ulasan: "Tempat duduknya lega dan pramugari sangat sopan.",
      rating: 4,
    },
    {
      id: 7,
      name: "Sari Puspita",
      maskapai: "Maskapai Sriwijaya Air",
      rute: "Penerbangan Palembang Jakarta",
      ulasan: "Penerbangan cukup baik, meskipun sedikit turbulensi.",
      rating: 3,
    },
    {
      id: 8,
      name: "Andi Rahmat",
      maskapai: "Maskapai Lion Air",
      rute: "Penerbangan Makassar Surabaya",
      ulasan: "Delay lumayan lama, tapi crew tetap profesional.",
      rating: 2,
    },
    {
      id: 9,
      name: "Melati Wulandari",
      maskapai: "Maskapai NAM Air",
      rute: "Penerbangan Jakarta Pontianak",
      ulasan: "Pelayanan cukup oke, tapi kursinya agak sempit.",
      rating: 3,
    },
    {
      id: 10,
      name: "Dian Saputra",
      maskapai: "Maskapai Super Air Jet",
      rute: "Penerbangan Jakarta Medan",
      ulasan: "Terbang perdana dengan Super Air Jet, lumayan juga ternyata.",
      rating: 4,
    },
    {
      id: 11,
      name: "Yuni Kurniawati",
      maskapai: "Maskapai Citilink",
      rute: "Penerbangan Bandung Surabaya",
      ulasan: "Boarding cepat dan tidak ribet, recommended!",
      rating: 5,
    },
  ];
  